export const games = [
  {
    id: 1,
    title: "The Witcher 3: Wild Hunt",
    genre: ["RPG", "Action"],
    platforms: ["PC", "PS4", "Xbox One", "Switch"],
    developer: "CD Projekt Red",
    releaseYear: 2015,
    rating: 9.8,
  },
  {
    id: 2,
    title: "God of War Ragnarok",
    genre: ["Action", "Adventure"],
    platforms: ["PS4", "PS5"],
    developer: "Santa Monica Studio",
    releaseYear: 2022,
    rating: 9.5,
  },
  {
    id: 3,
    title: "Elden Ring",
    genre: ["Action", "RPG"],
    platforms: ["PC", "PS4", "PS5", "Xbox"],
    developer: "FromSoftware",
    releaseYear: 2022,
    rating: 9.6,
  },
  {
    id: 4,
    title: "Red Dead Redemption 2",
    genre: ["Action", "Adventure"],
    platforms: ["PC", "PS4", "Xbox One"],
    developer: "Rockstar Games",
    releaseYear: 2018,
    rating: 9.7,
  },
  {
    id: 5,
    title: "Cyberpunk 2077",
    genre: ["RPG", "Action"],
    platforms: ["PC", "PS4", "PS5", "Xbox"],
    developer: "CD Projekt Red",
    releaseYear: 2020,
    rating: 8.5,
  },
  {
    id: 6,
    title: "Hades",
    genre: ["Roguelike", "Action"],
    platforms: ["PC", "Switch", "PS4", "PS5", "Xbox"],
    developer: "Supergiant Games",
    releaseYear: 2020,
    rating: 9.2,
  },
  {
    id: 7,
    title: "The Legend of Zelda: Breath of the Wild",
    genre: ["Adventure", "Action"],
    platforms: ["Switch", "Wii U"],
    developer: "Nintendo",
    releaseYear: 2017,
    rating: 9.9,
  },
  {
    id: 8,
    title: "Super Mario Odyssey",
    genre: ["Platformer"],
    platforms: ["Switch"],
    developer: "Nintendo",
    releaseYear: 2017,
    rating: 9.7,
  },
  {
    id: 9,
    title: "GTA V",
    genre: ["Action", "Open World"],
    platforms: ["PC", "PS3", "PS4", "PS5", "Xbox"],
    developer: "Rockstar Games",
    releaseYear: 2013,
    rating: 9.6,
  },
  {
    id: 10,
    title: "Minecraft",
    genre: ["Sandbox", "Survival"],
    platforms: ["PC", "Mobile", "Console"],
    developer: "Mojang",
    releaseYear: 2011,
    rating: 9.5,
  },
  {
    id: 11,
    title: "Fortnite",
    genre: ["Battle Royale", "Shooter"],
    platforms: ["PC", "Mobile", "Console"],
    developer: "Epic Games",
    releaseYear: 2017,
    rating: 8.2,
  },
  {
    id: 12,
    title: "Valorant",
    genre: ["Shooter", "Tactical"],
    platforms: ["PC"],
    developer: "Riot Games",
    releaseYear: 2020,
    rating: 8.6,
  },
  {
    id: 13,
    title: "Call of Duty: Modern Warfare II",
    genre: ["Shooter"],
    platforms: ["PC", "PS4", "PS5", "Xbox"],
    developer: "Infinity Ward",
    releaseYear: 2022,
    rating: 8.4,
  },
  {
    id: 14,
    title: "Apex Legends",
    genre: ["Battle Royale", "Shooter"],
    platforms: ["PC", "Console", "Mobile"],
    developer: "Respawn Entertainment",
    releaseYear: 2019,
    rating: 8.7,
  },
  {
    id: 15,
    title: "Assassin's Creed Valhalla",
    genre: ["Action", "RPG"],
    platforms: ["PC", "PS4", "PS5", "Xbox"],
    developer: "Ubisoft",
    releaseYear: 2020,
    rating: 8.3,
  },
  {
    id: 16,
    title: "Hollow Knight",
    genre: ["Metroidvania", "Platformer"],
    platforms: ["PC", "Switch", "PS4", "Xbox"],
    developer: "Team Cherry",
    releaseYear: 2017,
    rating: 9.0,
  },
  {
    id: 17,
    title: "Resident Evil Village",
    genre: ["Horror", "Action"],
    platforms: ["PC", "PS4", "PS5", "Xbox"],
    developer: "Capcom",
    releaseYear: 2021,
    rating: 8.8,
  },
  {
    id: 18,
    title: "Overwatch 2",
    genre: ["Shooter", "Multiplayer"],
    platforms: ["PC", "Console"],
    developer: "Blizzard",
    releaseYear: 2022,
    rating: 7.9,
  },
  {
    id: 19,
    title: "Stardew Valley",
    genre: ["Simulation", "Farming"],
    platforms: ["PC", "Mobile", "Console"],
    developer: "ConcernedApe",
    releaseYear: 2016,
    rating: 9.4,
  },
  {
    id: 20,
    title: "Terraria",
    genre: ["Adventure", "Sandbox"],
    platforms: ["PC", "Mobile", "Console"],
    developer: "Re-Logic",
    releaseYear: 2011,
    rating: 9.1,
  },
];

export const movies = [
  {
    id: 1,
    title: "Inception",
    genre: ["Sci-Fi", "Thriller"],
    director: "Christopher Nolan",
    releaseYear: 2010,
    rating: 8.8,
  },
  {
    id: 2,
    title: "The Dark Knight",
    genre: ["Action", "Crime"],
    director: "Christopher Nolan",
    releaseYear: 2008,
    rating: 9.0,
  },
  {
    id: 3,
    title: "Interstellar",
    genre: ["Sci-Fi", "Adventure"],
    director: "Christopher Nolan",
    releaseYear: 2014,
    rating: 8.6,
  },
  {
    id: 4,
    title: "Avengers: Endgame",
    genre: ["Action", "Sci-Fi"],
    director: "Anthony & Joe Russo",
    releaseYear: 2019,
    rating: 8.4,
  },
  {
    id: 5,
    title: "The Shawshank Redemption",
    genre: ["Drama"],
    director: "Frank Darabont",
    releaseYear: 1994,
    rating: 9.3,
  },
  {
    id: 6,
    title: "Parasite",
    genre: ["Thriller", "Drama"],
    director: "Bong Joon-ho",
    releaseYear: 2019,
    rating: 8.6,
  },
  {
    id: 7,
    title: "The Godfather",
    genre: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    releaseYear: 1972,
    rating: 9.2,
  },
  {
    id: 8,
    title: "Pulp Fiction",
    genre: ["Crime", "Drama"],
    director: "Quentin Tarantino",
    releaseYear: 1994,
    rating: 8.9,
  },
  {
    id: 9,
    title: "Forrest Gump",
    genre: ["Drama", "Romance"],
    director: "Robert Zemeckis",
    releaseYear: 1994,
    rating: 8.8,
  },
  {
    id: 10,
    title: "Fight Club",
    genre: ["Drama", "Thriller"],
    director: "David Fincher",
    releaseYear: 1999,
    rating: 8.8,
  },
  {
    id: 11,
    title: "The Matrix",
    genre: ["Action", "Sci-Fi"],
    director: "Wachowskis",
    releaseYear: 1999,
    rating: 8.7,
  },
  {
    id: 12,
    title: "The Lord of the Rings: The Return of the King",
    genre: ["Fantasy", "Adventure"],
    director: "Peter Jackson",
    releaseYear: 2003,
    rating: 8.9,
  },
  {
    id: 13,
    title: "Gladiator",
    genre: ["Action", "Drama"],
    director: "Ridley Scott",
    releaseYear: 2000,
    rating: 8.5,
  },
  {
    id: 14,
    title: "Titanic",
    genre: ["Drama", "Romance"],
    director: "James Cameron",
    releaseYear: 1997,
    rating: 7.9,
  },
  {
    id: 15,
    title: "Joker",
    genre: ["Crime", "Drama"],
    director: "Todd Phillips",
    releaseYear: 2019,
    rating: 8.4,
  },
  {
    id: 16,
    title: "Whiplash",
    genre: ["Drama", "Music"],
    director: "Damien Chazelle",
    releaseYear: 2014,
    rating: 8.5,
  },
  {
    id: 17,
    title: "La La Land",
    genre: ["Romance", "Music"],
    director: "Damien Chazelle",
    releaseYear: 2016,
    rating: 8.0,
  },
  {
    id: 18,
    title: "The Social Network",
    genre: ["Biography", "Drama"],
    director: "David Fincher",
    releaseYear: 2010,
    rating: 7.8,
  },
  {
    id: 19,
    title: "Spider-Man: No Way Home",
    genre: ["Action", "Adventure"],
    director: "Jon Watts",
    releaseYear: 2021,
    rating: 8.2,
  },
  {
    id: 20,
    title: "Oppenheimer",
    genre: ["Biography", "Drama", "History"],
    director: "Christopher Nolan",
    releaseYear: 2023,
    rating: 8.6,
  },
];
